/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectuastest;

/**
 *
 * @author all
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class fBuku extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection net = sync.sync();
    
    public fBuku(){
        initComponents();
        judul();
        autonum();
        tampilData("");
        setTitle("Form Data Buku");
        cbkategori();
        ibuku.setEditable(false);
        hapus.setEnabled(false);
        ubah.setEnabled(false);
        
    }
    //Tabel views
    private void tampilData(String string) {
         tabModel = (DefaultTableModel)tbbuku.getModel();
         tabModel.setRowCount(0);
         try {
             st = net.createStatement();
             rs = st.executeQuery("SELECT * FROM buku ");
             String id_buku;
             String judul;
             String ket_buku;
             String stat_buku;
             String id_kategori;
             while(rs.next()){
                 id_buku = rs.getString("id_buku");
                 judul = rs.getString("judul");
                 ket_buku = rs.getString("ket_buku");
                 stat_buku = rs.getString("stat_buku");
                 id_kategori = rs.getString("id_kategori");
                 tabModel.addRow(new Object[]{id_buku, judul, ket_buku,stat_buku, id_kategori });
             }
             
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
         }
         }
         
    // Metod search
         public void tampil() {
         tabModel = (DefaultTableModel)tbbuku.getModel();
         tabModel.setRowCount(0);
         String src = Ksearch.getText();
         try {
             st = net.createStatement();
             rs = st.executeQuery("SELECT * FROM buku WHERE judul LIKE '%"+src+"%'");
             String id_buku;
             String judul;
             String ket_buku;
             String stat_buku;
             String id_kategori;
             while(rs.next()){
                 id_buku = rs.getString("id_buku");
                 judul = rs.getString("judul");
                 ket_buku = rs.getString("ket_buku");
                 stat_buku = rs.getString("stat_buku");
                 id_kategori = rs.getString("id_kategori");
                 tabModel.addRow(new Object[]{id_buku, judul, ket_buku,stat_buku, id_kategori });
             }
             
         } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
         }
         }
    
    /**
     * Creates new form NewJFrame
     */
    // show on head table
    public void judul() {
    Object[] judul ={
    "id_buku", "judul", "ket_buku","stat_buku", "id_kategori"
    };
    tabModel = new DefaultTableModel(null,judul);
    tbbuku.setModel(tabModel);
    }
    public void reset(){
    ibuku.setText("");
    bnama.setText("");
    desbuku.setText("");
    statbuku.setText("");
    ikategori.setSelectedItem("--select id--");
    }
    
    //comboBox kategori connect to tb_kategori
    public void cbkategori(){
       try{
           st = net.createStatement();
           String sql = "SELECT * FROM kategori";
           rs = st.executeQuery(sql);
           
           while(rs.next()){
               ikategori.addItem(rs.getString("id_kategori"));     
           }
//           rs.last();
//           int jumlahdata = rs.getRow();
//           rs.first();
           
       }catch(Exception e){
           
       }
   }
    //sample code auto increment
    public void autonum(){
       try{
           String sql = "SELECT MAX(RIGHT(id_buku,2)) AS no_auto FROM buku ";
           st = net.createStatement();
           rs = st.executeQuery(sql);
           
           if(rs.next()){
               String no_auto,nol_plus;
               int p;
               no_auto = Integer.toString(rs.getInt(1)+1);
               p = no_auto.length();
               nol_plus = "";
               for(int i =0;i<=2 -p;i++){
                   nol_plus = nol_plus+"0";
               }
               ibuku.setText("BK"+nol_plus+no_auto);
           }
       } catch (Exception e) {
           ibuku.setText("BK001");
       }
       }
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        search = new javax.swing.JToggleButton();
        Ksearch = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        ibuku = new javax.swing.JTextField();
        IDBuku = new javax.swing.JLabel();
        bnama = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        desbuku = new javax.swing.JTextField();
        telepon = new javax.swing.JLabel();
        statbuku = new javax.swing.JTextField();
        keterangan = new javax.swing.JLabel();
        reset = new javax.swing.JToggleButton();
        keterangan1 = new javax.swing.JLabel();
        ikategori = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbbuku = new javax.swing.JTable();
        ubah = new javax.swing.JToggleButton();
        hapus = new javax.swing.JToggleButton();
        tambah = new javax.swing.JToggleButton();
        Home = new javax.swing.JButton();
        Datauser = new javax.swing.JButton();
        Kategori = new javax.swing.JButton();
        Pinjam = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("Data Buku");

        jPanel2.setBackground(new java.awt.Color(255, 153, 153));

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        Ksearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KsearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Ksearch, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Ksearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        ibuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibukuActionPerformed(evt);
            }
        });

        IDBuku.setText("ID Buku");

        nama.setText("Judul");

        telepon.setText("Deskripsi");

        statbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statbukuActionPerformed(evt);
            }
        });

        keterangan.setText("Stat Buku");

        reset.setText("reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        keterangan1.setText("ID Kategori");

        ikategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--select id--" }));
        ikategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ikategoriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(IDBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ibuku, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(telepon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(desbuku, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bnama, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(keterangan)
                            .addComponent(keterangan1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(statbuku)
                            .addComponent(ikategori, 0, 371, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDBuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telepon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keterangan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keterangan1)
                    .addComponent(ikategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(reset)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jScrollPane2.setEnabled(false);

        tbbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul", "Deskripsi", "Stat buku", "ID Kategori"
            }
        ));
        tbbuku.setCellSelectionEnabled(true);
        tbbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbbuku);
        tbbuku.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ubah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(tambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });

        Datauser.setText("Data User");
        Datauser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatauserActionPerformed(evt);
            }
        });

        Kategori.setText("Kategori");
        Kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriActionPerformed(evt);
            }
        });

        Pinjam.setText("Pinjam");
        Pinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PinjamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(118, 118, 118)
                        .addComponent(Home)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Datauser)
                        .addGap(18, 18, 18)
                        .addComponent(Kategori)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Pinjam)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Home)
                            .addComponent(Datauser)
                            .addComponent(Kategori)
                            .addComponent(Pinjam)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(739, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_searchActionPerformed

    private void KsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KsearchActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        // TODO add your handling code here:
        try{
        st = net.createStatement();
        st.executeUpdate("Update buku set id_buku ='"+ibuku.getText()+"', judul = '"+bnama.getText()+"', ket_buku ='"+desbuku.getText()+"', stat_buku ='"+statbuku.getText()+"', id_kategori ='"+ikategori.getSelectedItem()+
                "' WHERE id_buku = '"+ibuku.getText()+"'");
        tampilData("");
        JOptionPane.showMessageDialog(null, "Update Berhasil");
        reset();
        autonum();
        }catch(Exception e){
        e.printStackTrace();}
                                           
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try{
        int jawab;
        
        if((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data ?","konfirmasi",JOptionPane.YES_NO_OPTION))==0){
        st = net.createStatement();
        st.executeUpdate("DELETE FROM buku WHERE id_buku='"
        +tabModel.getValueAt(tbbuku.getSelectedRow(),0)+ "'");
        tampilData("");
        reset();
        autonum();
        }
        }catch(Exception e){
        e.printStackTrace();}
    }//GEN-LAST:event_hapusActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        try{
        st=net.createStatement();
        st.executeUpdate("INSERT INTO buku VALUES (' "+ibuku.getText()+"','"
        + bnama.getText()+"','"+ desbuku.getText()+"','"+ statbuku.getText()+"','"
        + ikategori.getSelectedItem()+"')");
        tampilData("");
        JOptionPane.showMessageDialog(null, "Data berasal disimpan");
        reset();
        autonum();
        }catch (Exception e){
        e.printStackTrace();
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        reset();
        autonum();
    }//GEN-LAST:event_resetActionPerformed

    private void PinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PinjamActionPerformed
        // TODO add your handling code here:
        fPinjam fp = new fPinjam();
        fp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PinjamActionPerformed

    private void statbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statbukuActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        fHome fh = new fHome();
        fh.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeActionPerformed

    private void ikategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ikategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ikategoriActionPerformed

    private void tbbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbukuMouseClicked
        // TODO add your handling code here:
        ibuku.setText(tbbuku.getValueAt(tbbuku.getSelectedRow(),0).toString());
        bnama.setText(tbbuku.getValueAt(tbbuku.getSelectedRow(),1).toString());
        desbuku.setText(tbbuku.getValueAt(tbbuku.getSelectedRow(),2).toString());
        statbuku.setText(tbbuku.getValueAt(tbbuku.getSelectedRow(),3).toString());
        ikategori.setSelectedItem(tbbuku.getValueAt(tbbuku.getSelectedRow(),4).toString());
        tambah.setEnabled(true);
        ubah.setEnabled(true);
        hapus.setEnabled(true);
    }//GEN-LAST:event_tbbukuMouseClicked

    private void KategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriActionPerformed
        // TODO add your handling code here:
        fKategori pk = new fKategori();
        pk.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_KategoriActionPerformed

    private void DatauserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatauserActionPerformed
        // TODO add your handling code here:
        fUser fu = new fUser();
        fu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DatauserActionPerformed

    private void ibukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Datauser;
    private javax.swing.JButton Home;
    private javax.swing.JLabel IDBuku;
    private javax.swing.JButton Kategori;
    private javax.swing.JTextField Ksearch;
    private javax.swing.JButton Pinjam;
    private javax.swing.JTextField bnama;
    private javax.swing.JTextField desbuku;
    private javax.swing.JToggleButton hapus;
    private javax.swing.JTextField ibuku;
    private javax.swing.JComboBox<String> ikategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel keterangan;
    private javax.swing.JLabel keterangan1;
    private javax.swing.JLabel nama;
    private javax.swing.JToggleButton reset;
    private javax.swing.JToggleButton search;
    private javax.swing.JTextField statbuku;
    private javax.swing.JToggleButton tambah;
    private javax.swing.JTable tbbuku;
    private javax.swing.JLabel telepon;
    private javax.swing.JToggleButton ubah;
    // End of variables declaration//GEN-END:variables
}
